/**
 * Letter export — renders a SavedLetter as a self-contained HTML document
 * the user can save locally, open in a browser, and (via the browser's
 * own print-to-PDF) keep as a permanent artifact.
 *
 * Design choices:
 *   - Pure render function. Takes a letter, returns HTML string. No IO.
 *   - Self-contained: all styling inlined. The file works offline, in
 *     any browser, with no external assets.
 *   - Typography that reads like a letter: serif body, generous line-
 *     height, narrow content column, calm header.
 *   - 5-locale safe — uses CSS font-family stacks that handle CJK + Latin
 *     gracefully without forcing webfont downloads.
 *   - The six paragraphs (greeting / summary / suggestion / intention /
 *     experiment / closing) render in fixed order with subtle dividers.
 *   - Output is intentionally light — the artifact-craft thesis is that
 *     the letter itself is the keepsake; ornamentation distracts.
 */

import type { SavedLetter } from './letterStore.ts'
import type { UiLanguage } from '../../types'
import {
  ARTIFACT_SANS_FONT_STACK,
  ARTIFACT_SERIF_FONT_STACK,
} from '../../lib/artifactStyles.ts'

interface LocaleStrings {
  /** Header label rendered above the date. */
  pageHeader: string
  /** Footer attribution. */
  footerCredit: string
  /** Date format option for `Intl.DateTimeFormat`. */
  dateLocale: string
}

const LOCALE_STRINGS: Record<UiLanguage, LocaleStrings> = {
  'en-US': {
    pageHeader: 'A letter from Nexus',
    footerCredit: 'Generated by Nexus — your local-first companion.',
    dateLocale: 'en-US',
  },
  'zh-CN': {
    pageHeader: 'Nexus 给你的一封信',
    footerCredit: '由 Nexus 生成 —— 留在本地的陪伴。',
    dateLocale: 'zh-CN',
  },
  'zh-TW': {
    pageHeader: 'Nexus 給你的一封信',
    footerCredit: '由 Nexus 生成 —— 留在本地的陪伴。',
    dateLocale: 'zh-TW',
  },
  'ja': {
    pageHeader: 'Nexus からの手紙',
    footerCredit: 'Nexus によって生成 — ローカルにとどまるあなたの伴走者。',
    dateLocale: 'ja-JP',
  },
  'ko': {
    pageHeader: 'Nexus가 보낸 편지',
    footerCredit: 'Nexus 생성 — 로컬에 머무는 당신의 동반자.',
    dateLocale: 'ko-KR',
  },
}

function pickLocale(uiLanguage: UiLanguage): LocaleStrings {
  return LOCALE_STRINGS[uiLanguage] ?? LOCALE_STRINGS['en-US']
}

/**
 * HTML-escape user-controlled strings so a stray `<script>` in a letter
 * body can't render as markup. Conservative pass — the SavedLetter
 * content is already produced by our prompt builder, but defence in
 * depth is cheap.
 */
export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function formatLetterDate(letterDate: string, dateLocale: string): string {
  const t = Date.parse(letterDate)
  if (!Number.isFinite(t)) return letterDate
  try {
    return new Intl.DateTimeFormat(dateLocale, {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }).format(new Date(t))
  } catch {
    return letterDate
  }
}

const STYLES = `
  :root {
    color-scheme: light;
  }
  body {
    margin: 0;
    background: #f5f3ee;
    color: #2a2a2a;
    font-family: ${ARTIFACT_SERIF_FONT_STACK};
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }
  main {
    max-width: 620px;
    margin: 64px auto;
    padding: 56px 60px;
    background: #fffdf9;
    border-radius: 4px;
    box-shadow: 0 2px 16px rgba(0, 0, 0, 0.06);
  }
  header {
    text-align: center;
    margin-bottom: 36px;
    padding-bottom: 24px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.08);
  }
  header .eyebrow {
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.18em;
    color: rgba(0, 0, 0, 0.45);
    font-family: ${ARTIFACT_SANS_FONT_STACK};
    margin-bottom: 14px;
  }
  header .date {
    font-size: 17px;
    color: rgba(0, 0, 0, 0.7);
    font-style: italic;
  }
  .body {
    font-size: 17px;
    line-height: 1.75;
  }
  .body p {
    margin: 0 0 1.4em 0;
  }
  .body p:last-child {
    margin-bottom: 0;
  }
  .closing {
    margin-top: 32px;
    padding-top: 24px;
    border-top: 1px solid rgba(0, 0, 0, 0.08);
    font-style: italic;
    color: rgba(0, 0, 0, 0.7);
  }
  footer {
    max-width: 620px;
    margin: 0 auto 64px;
    padding: 20px 60px;
    text-align: center;
    font-size: 12px;
    color: rgba(0, 0, 0, 0.4);
    font-family: ${ARTIFACT_SANS_FONT_STACK};
  }
  @media print {
    body { background: #fffdf9; }
    main { box-shadow: none; margin: 0 auto; }
    footer { display: none; }
  }
`

/**
 * Generate the export filename for a letter. Stable, locale-aware,
 * filesystem-safe. Used by both the IPC save call and the browser
 * download fallback.
 */
export function buildLetterFilename(letter: SavedLetter): string {
  const date = letter.letterDate.replace(/[^0-9-]/g, '') || 'letter'
  return `nexus-letter-${date}.html`
}

/**
 * Render a SavedLetter as a self-contained HTML document.
 */
export function renderLetterHtml(letter: SavedLetter): string {
  const locale = pickLocale(letter.uiLanguage)
  const formattedDate = formatLetterDate(letter.letterDate, locale.dateLocale)

  const paragraphs: ReadonlyArray<{ text: string; closing?: boolean }> = [
    { text: letter.content.greeting },
    { text: letter.content.summary },
    { text: letter.content.suggestion },
    { text: letter.content.intention },
    { text: letter.content.experiment },
    { text: letter.content.closing, closing: true },
  ]

  const bodyHtml = paragraphs
    .filter((p) => p.text && p.text.trim().length > 0)
    .map((p) => {
      const escaped = escapeHtml(p.text.trim())
      const cls = p.closing ? 'closing' : ''
      return cls ? `<p class="${cls}">${escaped}</p>` : `<p>${escaped}</p>`
    })
    .join('\n      ')

  return `<!DOCTYPE html>
<html lang="${escapeHtml(letter.uiLanguage)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(locale.pageHeader)} — ${escapeHtml(formattedDate)}</title>
  <style>${STYLES}</style>
</head>
<body>
  <main>
    <header>
      <div class="eyebrow">${escapeHtml(locale.pageHeader)}</div>
      <div class="date">${escapeHtml(formattedDate)}</div>
    </header>
    <div class="body">
      ${bodyHtml}
    </div>
  </main>
  <footer>${escapeHtml(locale.footerCredit)}</footer>
</body>
</html>
`
}
