import assert from 'node:assert/strict'
import { test } from 'node:test'

import {
  buildPatternComparison,
  formatPatternComparison,
} from '../scripts/open-source-ui-reference-patterns.mjs'

test('open-source pattern comparison maps surfaces and references both ways', () => {
  const comparison = buildPatternComparison()
  const formatted = formatPatternComparison(comparison)
  const composer = comparison.surfaces.find((surface) => surface.surface === 'composer')
  const lobeChat = comparison.references.find((reference) => reference.reference === 'LobeHub / LobeChat lineage')
  const companionTone = comparison.surfaces.find((surface) => surface.surface === 'companion-tone')
  const openHands = comparison.references.find((reference) => reference.reference === 'OpenHands')
  const libreChat = comparison.references.find((reference) => reference.reference === 'LibreChat')
  const cline = comparison.references.find((reference) => reference.reference === 'Cline')
  const companionToneAxis = comparison.axes.find((axis) => axis.axis === 'companion-tone')
  const streamingAxis = comparison.axes.find((axis) => axis.axis === 'streaming-boundaries')
  const agentActivityAxis = comparison.axes.find((axis) => axis.axis === 'agent-activity-boundaries')
  const approvalAxis = comparison.axes.find((axis) => axis.axis === 'agent-approval-boundaries')
  const conversationBoundaryAxis = comparison.axes.find((axis) => axis.axis === 'conversation-product-boundaries')

  assert.equal(comparison.surfaces.length, 10)
  assert.ok(comparison.guardrails.includes('Borrow constraints, not skins.'))
  assert.deepEqual(composer?.references, ['Chatbox', 'Jan', 'Vercel AI Chatbot', 'assistant-ui', 'LibreChat'])
  assert.deepEqual(companionTone?.references, ['LobeHub / LobeChat lineage', 'Jan', 'Chatbox'])
  assert.ok(lobeChat?.surfaces.includes('image4-presence'))
  assert.ok(lobeChat?.surfaces.includes('dial'))
  assert.ok(lobeChat?.surfaces.includes('companion-tone'))
  assert.ok(openHands?.surfaces.includes('agent-activity'))
  assert.ok(libreChat?.surfaces.includes('composer'))
  assert.ok(libreChat?.surfaces.includes('agent-activity'))
  assert.ok(cline?.surfaces.includes('focus-management'))
  assert.ok(cline?.surfaces.includes('agent-activity'))
  assert.ok(streamingAxis?.references.includes('assistant-ui'))
  assert.ok(companionToneAxis?.surfaces.includes('companion-tone'))
  assert.ok(companionToneAxis?.references.includes('LobeHub / LobeChat lineage'))
  assert.ok(streamingAxis?.references.includes('LibreChat'))
  assert.ok(streamingAxis?.surfaces.includes('streaming'))
  assert.ok(agentActivityAxis?.surfaces.includes('agent-activity'))
  assert.ok(approvalAxis?.references.includes('Cline'))
  assert.ok(approvalAxis?.surfaces.includes('focus-management'))
  assert.ok(conversationBoundaryAxis?.references.includes('LibreChat'))
  assert.ok(lobeChat?.patterns.some((pattern) => pattern.nexusMapping.includes('only 星绘')))
  assert.ok(lobeChat?.patterns.some((pattern) => pattern.nexusMapping.includes('Morning warmth')))
  assert.ok(lobeChat?.patterns.some((pattern) => pattern.avoid.includes('right-side orbit dots')))
  assert.ok(lobeChat?.patterns.some((pattern) => pattern.avoid.includes('Sampling reference palettes')))
  assert.ok(composer?.patterns.some((pattern) => pattern.nexusMapping.includes('embedded tools')))
  assert.ok(composer?.patterns.some((pattern) => pattern.avoid.includes('ChatGPT-like input skin')))
  assert.ok(composer?.patterns.some((pattern) => pattern.avoid.includes('separate default tool tiles')))
  assert.match(formatted, /Open-source cross-surface pattern comparison/)
  assert.match(formatted, /By surface:/)
  assert.match(formatted, /By paradigm axis:/)
  assert.match(formatted, /By reference:/)
  assert.match(formatted, /Do not copy exact spacing/)
})

test('open-source pattern comparison keeps every pattern mapped and bounded', () => {
  const comparison = buildPatternComparison()
  const allPatterns = comparison.surfaces.flatMap((surface) => surface.patterns)

  assert.ok(allPatterns.length >= comparison.surfaces.length)
  assert.ok(allPatterns.every((pattern) => pattern.reference.length > 0))
  assert.ok(allPatterns.every((pattern) => pattern.axis.length > 0))
  assert.ok(allPatterns.every((pattern) => pattern.pattern.length > 0))
  assert.ok(allPatterns.every((pattern) => pattern.nexusMapping.length > 0))
  assert.ok(allPatterns.every((pattern) => pattern.avoid.length > 0))
  assert.ok(allPatterns.some((pattern) => pattern.avoid.includes('Avatar chrome')))
  assert.ok(allPatterns.some((pattern) => pattern.avoid.includes('Default demo skin')))
  assert.ok(comparison.axes.some((axis) => axis.axis === 'desktop-locality'))
  assert.ok(comparison.axes.some((axis) => axis.axis === 'companion-tone'))
  assert.ok(comparison.axes.some((axis) => axis.axis === 'context-boundaries'))
  assert.ok(comparison.axes.some((axis) => axis.axis === 'agent-activity-boundaries'))
  assert.ok(comparison.axes.some((axis) => axis.axis === 'agent-approval-boundaries'))
  assert.ok(comparison.axes.some((axis) => axis.axis === 'conversation-product-boundaries'))
})
