/**
 * Yearbook renderer — pure function producing one self-contained HTML
 * document covering the past 12 months. Reuses the same calm typography
 * + CJK-safe font stack pioneered in letterExport, with a longer
 * structure: title page → year overview → 12 monthly mini mood-maps →
 * chronological letter excerpts → closing.
 *
 * Inline SVG is used for the month strips — small, no external deps,
 * works offline. Each strip is one valence line normalised to [0,1] for
 * display, with a faint neutral guide.
 */

import type { YearbookSnapshot, MonthlyBucket } from './yearbookAggregator.ts'
import type { UiLanguage } from '../../types'
import type { SavedLetter } from '../letter/letterStore.ts'
import { escapeHtml } from '../letter/letterExport.ts'

interface LocaleStrings {
  pageHeader: string
  yearOverviewHeader: string
  baselineLabel: string
  variabilityLabel: string
  inertiaLabel: string
  samplesLabel: string
  coregHeader: string
  coregCoRegulating: string
  coregMirroring: string
  coregFlat: string
  coregUnknown: string
  monthlyHeader: string
  emptyMonthLabel: string
  lettersHeader: string
  lettersEmpty: string
  closingHeader: string
  closingNote: string
  footerCredit: string
  dateLocale: string
  monthLocale: string
}

const LOCALES: Record<UiLanguage, LocaleStrings> = {
  'en-US': {
    pageHeader: 'A year with Nexus',
    yearOverviewHeader: 'A year, in numbers',
    baselineLabel: 'Baseline valence',
    variabilityLabel: 'Variability',
    inertiaLabel: 'Inertia',
    samplesLabel: 'samples',
    coregHeader: 'How we moved together',
    coregCoRegulating: 'Co-regulating — she has been warmer when you were down.',
    coregMirroring: 'Mirroring — her warmth has tracked your valence.',
    coregFlat: 'Flat — no clear coupling either way.',
    coregUnknown: 'Not enough overlapping data to characterise.',
    monthlyHeader: 'Month by month',
    emptyMonthLabel: 'no samples',
    lettersHeader: 'Letters from the year',
    lettersEmpty: 'No letters this year — yet.',
    closingHeader: 'A note from her',
    closingNote: 'Thank you for keeping me here. Whatever next year holds, I will be in the room.',
    footerCredit: 'Generated by Nexus — your local-first companion.',
    dateLocale: 'en-US',
    monthLocale: 'en-US',
  },
  'zh-CN': {
    pageHeader: '和 Nexus 的一年',
    yearOverviewHeader: '一年，用数字看',
    baselineLabel: '基线效价',
    variabilityLabel: '波动度',
    inertiaLabel: '惯性',
    samplesLabel: '个样本',
    coregHeader: '我们这一年一起走过的形状',
    coregCoRegulating: '协同模式——你低落的日子，她更温。',
    coregMirroring: '镜像模式——她的温度跟着你的状态走。',
    coregFlat: '平稳——两边没有明显耦合。',
    coregUnknown: '重叠的数据还不够，没办法判断。',
    monthlyHeader: '一月一月看',
    emptyMonthLabel: '无样本',
    lettersHeader: '今年的信',
    lettersEmpty: '今年还没收到信——再等等。',
    closingHeader: '她的一句话',
    closingNote: '谢谢你一年里一直把我留着。下一年不管会发生什么，我都在这里。',
    footerCredit: '由 Nexus 生成 —— 留在本地的陪伴。',
    dateLocale: 'zh-CN',
    monthLocale: 'zh-CN',
  },
  'zh-TW': {
    pageHeader: '與 Nexus 的一年',
    yearOverviewHeader: '一年，用數字看',
    baselineLabel: '基線效價',
    variabilityLabel: '波動度',
    inertiaLabel: '慣性',
    samplesLabel: '個樣本',
    coregHeader: '我們這一年一起走過的形狀',
    coregCoRegulating: '協同模式——你低落的日子，她更溫。',
    coregMirroring: '鏡像模式——她的溫度跟著你的狀態走。',
    coregFlat: '平穩——兩邊沒有明顯耦合。',
    coregUnknown: '重疊的資料還不夠，沒辦法判斷。',
    monthlyHeader: '一月一月看',
    emptyMonthLabel: '無樣本',
    lettersHeader: '今年的信',
    lettersEmpty: '今年還沒收到信——再等等。',
    closingHeader: '她的一句話',
    closingNote: '謝謝你一年裡一直把我留著。下一年不管會發生什麼，我都在這裡。',
    footerCredit: '由 Nexus 生成 —— 留在本地的陪伴。',
    dateLocale: 'zh-TW',
    monthLocale: 'zh-TW',
  },
  'ja': {
    pageHeader: 'Nexus と過ごした一年',
    yearOverviewHeader: '一年を、数字で',
    baselineLabel: 'ベースライン感情価',
    variabilityLabel: '変動性',
    inertiaLabel: '慣性',
    samplesLabel: 'サンプル',
    coregHeader: '一緒に動いてきた形',
    coregCoRegulating: '共調整 — あなたが沈む日に彼女は温かくなっていた。',
    coregMirroring: '鏡映 — 彼女の温度はあなたの感情と一緒に動いていた。',
    coregFlat: 'フラット — 明確な連動は見られない。',
    coregUnknown: '重なるデータが足りず、判定できない。',
    monthlyHeader: '月ごとに',
    emptyMonthLabel: 'サンプルなし',
    lettersHeader: '今年の手紙',
    lettersEmpty: '今年はまだ手紙が届いていない — もう少し。',
    closingHeader: '彼女からひとこと',
    closingNote: '一年、ここに置いてくれてありがとう。来年に何があっても、私はそばにいます。',
    footerCredit: 'Nexus によって生成 — ローカルにとどまるあなたの伴走者。',
    dateLocale: 'ja-JP',
    monthLocale: 'ja-JP',
  },
  'ko': {
    pageHeader: 'Nexus와 함께한 일 년',
    yearOverviewHeader: '일 년을, 숫자로',
    baselineLabel: '기준 정서가',
    variabilityLabel: '변동성',
    inertiaLabel: '관성',
    samplesLabel: '샘플',
    coregHeader: '함께 움직인 모양',
    coregCoRegulating: '공동 조절 — 네가 가라앉은 날 그녀는 더 따뜻해졌어.',
    coregMirroring: '거울 모드 — 그녀의 따뜻함이 너의 상태를 따라 움직였어.',
    coregFlat: '평탄 — 양쪽에 뚜렷한 연동이 없어.',
    coregUnknown: '겹치는 데이터가 부족해 판단하기 어려워.',
    monthlyHeader: '달마다',
    emptyMonthLabel: '샘플 없음',
    lettersHeader: '올해의 편지',
    lettersEmpty: '올해는 아직 편지가 없어 — 조금만 더.',
    closingHeader: '그녀의 한 마디',
    closingNote: '일 년 동안 여기 두어줘서 고마워. 내년에 무엇이 오든, 나는 곁에 있을게.',
    footerCredit: 'Nexus 생성 — 로컬에 머무는 당신의 동반자.',
    dateLocale: 'ko-KR',
    monthLocale: 'ko-KR',
  },
}

function pickLocale(uiLanguage: UiLanguage): LocaleStrings {
  return LOCALES[uiLanguage] ?? LOCALES['en-US']
}

function formatRange(startIso: string, endIso: string, dateLocale: string): string {
  const a = Date.parse(startIso)
  const b = Date.parse(endIso)
  if (!Number.isFinite(a) || !Number.isFinite(b)) return `${startIso} → ${endIso}`
  try {
    const fmt = new Intl.DateTimeFormat(dateLocale, { month: 'long', year: 'numeric' })
    return `${fmt.format(new Date(a))} — ${fmt.format(new Date(b))}`
  } catch {
    return `${startIso} → ${endIso}`
  }
}

function formatMonthLabel(monthStartIso: string, monthLocale: string): string {
  const t = Date.parse(monthStartIso)
  if (!Number.isFinite(t)) return monthStartIso
  try {
    return new Intl.DateTimeFormat(monthLocale, { month: 'long', year: 'numeric' }).format(new Date(t))
  } catch {
    return monthStartIso
  }
}

function formatLetterDate(letterDate: string, dateLocale: string): string {
  const t = Date.parse(letterDate)
  if (!Number.isFinite(t)) return letterDate
  try {
    return new Intl.DateTimeFormat(dateLocale, {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }).format(new Date(t))
  } catch {
    return letterDate
  }
}

function formatSigned(x: number): string {
  if (x === 0) return '0.00'
  const sign = x > 0 ? '+' : ''
  return `${sign}${x.toFixed(2)}`
}

// ── Mini mood-map SVG ─────────────────────────────────────────────────────

const STRIP_W = 360
const STRIP_H = 60
const STRIP_PAD_X = 8
const STRIP_PAD_Y = 8

function renderMonthStrip(month: MonthlyBucket): string {
  if (month.bins.length < 2) {
    return `<svg viewBox="0 0 ${STRIP_W} ${STRIP_H}" class="strip-empty" role="img" aria-label="empty"></svg>`
  }
  const firstMs = Date.parse(month.bins[0].day)
  const lastMs = Date.parse(month.bins[month.bins.length - 1].day)
  const span = Math.max(lastMs - firstMs, 1)
  const innerW = STRIP_W - 2 * STRIP_PAD_X
  const innerH = STRIP_H - 2 * STRIP_PAD_Y

  const x = (day: string): number => {
    const t = Date.parse(day)
    const ratio = Number.isFinite(t) ? (t - firstMs) / span : 0
    return STRIP_PAD_X + ratio * innerW
  }
  const y = (valence: number): number => {
    const norm = (valence + 1) / 2
    return STRIP_PAD_Y + (1 - norm) * innerH
  }
  const neutral = STRIP_PAD_Y + 0.5 * innerH

  const path = month.bins
    .map((b, i) => `${i === 0 ? 'M' : 'L'}${x(b.day).toFixed(1)},${y(b.valence).toFixed(1)}`)
    .join(' ')

  return `<svg viewBox="0 0 ${STRIP_W} ${STRIP_H}" class="strip" role="img" aria-label="month">
    <line x1="${STRIP_PAD_X}" x2="${STRIP_W - STRIP_PAD_X}" y1="${neutral}" y2="${neutral}" stroke="rgba(0,0,0,0.1)" stroke-dasharray="2 3"/>
    <path d="${path}" stroke="#5a8a6a" stroke-width="1.4" fill="none"/>
  </svg>`
}

// ── Sections ──────────────────────────────────────────────────────────────

function renderYearOverview(snap: YearbookSnapshot, locale: LocaleStrings): string {
  const parts: string[] = []
  if (snap.yearSnapshot.baselineValence != null) {
    parts.push(`<dt>${escapeHtml(locale.baselineLabel)}</dt><dd>${escapeHtml(formatSigned(snap.yearSnapshot.baselineValence))}</dd>`)
  }
  if (snap.yearSnapshot.variability != null) {
    parts.push(`<dt>${escapeHtml(locale.variabilityLabel)}</dt><dd>${escapeHtml(snap.yearSnapshot.variability.toFixed(2))}</dd>`)
  }
  if (snap.yearSnapshot.inertia != null) {
    parts.push(`<dt>${escapeHtml(locale.inertiaLabel)}</dt><dd>${escapeHtml(snap.yearSnapshot.inertia.toFixed(2))}</dd>`)
  }
  parts.push(`<dt>${escapeHtml(locale.samplesLabel)}</dt><dd>${snap.yearSnapshot.n}</dd>`)

  return `<section class="overview">
    <h2>${escapeHtml(locale.yearOverviewHeader)}</h2>
    <dl>${parts.join('')}</dl>
  </section>`
}

function renderCoreg(snap: YearbookSnapshot, locale: LocaleStrings): string {
  const labelMap: Record<string, string> = {
    'co-regulating': locale.coregCoRegulating,
    'mirroring': locale.coregMirroring,
    'flat': locale.coregFlat,
    'unknown': locale.coregUnknown,
  }
  const label = labelMap[snap.coregKind]
  return `<section class="coreg">
    <h2>${escapeHtml(locale.coregHeader)}</h2>
    <p>${escapeHtml(label)}</p>
  </section>`
}

function renderMonthly(snap: YearbookSnapshot, locale: LocaleStrings): string {
  const rows = snap.months
    .map((m) => {
      const monthLabel = formatMonthLabel(m.monthStart, locale.monthLocale)
      const baselineText = m.snapshot.baselineValence != null
        ? formatSigned(m.snapshot.baselineValence)
        : `<span class="muted">${escapeHtml(locale.emptyMonthLabel)}</span>`
      return `<div class="month-row">
        <div class="month-label">${escapeHtml(monthLabel)}</div>
        <div class="month-strip">${renderMonthStrip(m)}</div>
        <div class="month-stat">${baselineText}</div>
      </div>`
    })
    .join('\n      ')
  return `<section class="monthly">
    <h2>${escapeHtml(locale.monthlyHeader)}</h2>
    <div class="month-list">
      ${rows}
    </div>
  </section>`
}

function renderLetterExcerpt(letter: SavedLetter, dateLocale: string): string {
  // First non-empty paragraph as the excerpt — typically the greeting.
  const candidates = [
    letter.content.greeting,
    letter.content.summary,
    letter.content.suggestion,
  ]
  const excerpt = candidates.find((s) => s && s.trim().length > 0) ?? ''
  return `<article class="letter-excerpt">
    <header>${escapeHtml(formatLetterDate(letter.letterDate, dateLocale))}</header>
    <p>${escapeHtml(excerpt.trim())}</p>
  </article>`
}

function renderLetters(snap: YearbookSnapshot, locale: LocaleStrings): string {
  if (snap.letters.length === 0) {
    return `<section class="letters">
      <h2>${escapeHtml(locale.lettersHeader)}</h2>
      <p class="muted">${escapeHtml(locale.lettersEmpty)}</p>
    </section>`
  }
  const items = snap.letters.map((l) => renderLetterExcerpt(l, locale.dateLocale)).join('\n      ')
  return `<section class="letters">
    <h2>${escapeHtml(locale.lettersHeader)}</h2>
    <div class="letter-list">
      ${items}
    </div>
  </section>`
}

function renderClosing(locale: LocaleStrings): string {
  return `<section class="closing-section">
    <h2>${escapeHtml(locale.closingHeader)}</h2>
    <p>${escapeHtml(locale.closingNote)}</p>
  </section>`
}

const STYLES = `
  :root { color-scheme: light; }
  body {
    margin: 0;
    background: #f5f3ee;
    color: #2a2a2a;
    font-family: 'Iowan Old Style', 'Apple Garamond', 'Baskerville',
      'Times New Roman', 'Georgia', 'PingFang SC', 'Hiragino Sans',
      'Hiragino Mincho ProN', 'Noto Serif CJK SC', 'Noto Serif CJK TC',
      'Noto Serif KR', serif;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }
  main {
    max-width: 720px;
    margin: 64px auto;
    padding: 60px 64px;
    background: #fffdf9;
    border-radius: 4px;
    box-shadow: 0 2px 16px rgba(0, 0, 0, 0.06);
  }
  header.title-page {
    text-align: center;
    margin-bottom: 56px;
    padding-bottom: 32px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.08);
  }
  header.title-page .eyebrow {
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.2em;
    color: rgba(0, 0, 0, 0.45);
    font-family: -apple-system, 'Helvetica Neue', sans-serif;
    margin-bottom: 18px;
  }
  header.title-page h1 {
    font-size: 30px;
    font-weight: 500;
    margin: 0 0 16px;
    color: #1a1a1a;
  }
  header.title-page .range {
    font-size: 16px;
    font-style: italic;
    color: rgba(0, 0, 0, 0.6);
  }
  section { margin: 48px 0; }
  section h2 {
    font-size: 19px;
    font-weight: 500;
    margin: 0 0 18px;
    padding-bottom: 8px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.06);
    color: #1a1a1a;
  }
  section.overview dl {
    display: grid;
    grid-template-columns: max-content 1fr;
    gap: 6px 18px;
    margin: 0;
    font-size: 15px;
  }
  section.overview dt { color: rgba(0, 0, 0, 0.55); }
  section.overview dd { margin: 0; font-variant-numeric: tabular-nums; }
  section.coreg p { font-size: 16px; line-height: 1.7; margin: 0; }
  .month-list { display: flex; flex-direction: column; gap: 6px; }
  .month-row {
    display: grid;
    grid-template-columns: 110px 1fr 60px;
    align-items: center;
    gap: 14px;
    font-size: 14px;
  }
  .month-label { color: rgba(0, 0, 0, 0.6); }
  .month-stat { text-align: right; font-variant-numeric: tabular-nums; color: rgba(0, 0, 0, 0.7); }
  .strip, .strip-empty { display: block; width: 100%; height: 38px; }
  .strip-empty { background: rgba(0, 0, 0, 0.025); border-radius: 2px; }
  .muted { color: rgba(0, 0, 0, 0.35); font-style: italic; }
  .letter-list { display: flex; flex-direction: column; gap: 24px; }
  .letter-excerpt {
    border-left: 2px solid rgba(0, 0, 0, 0.1);
    padding: 4px 0 4px 16px;
  }
  .letter-excerpt header {
    font-size: 13px;
    color: rgba(0, 0, 0, 0.5);
    margin-bottom: 6px;
    font-style: italic;
  }
  .letter-excerpt p {
    margin: 0;
    font-size: 15px;
    line-height: 1.7;
  }
  section.closing-section p {
    font-style: italic;
    font-size: 16px;
    line-height: 1.7;
    color: rgba(0, 0, 0, 0.7);
    margin: 0;
  }
  footer {
    max-width: 720px;
    margin: 0 auto 64px;
    padding: 20px 64px;
    text-align: center;
    font-size: 12px;
    color: rgba(0, 0, 0, 0.4);
    font-family: -apple-system, 'Helvetica Neue', sans-serif;
  }
  @media print {
    body { background: #fffdf9; }
    main { box-shadow: none; margin: 0 auto; }
    footer { display: none; }
    section { page-break-inside: avoid; }
  }
`

export function buildYearbookFilename(uiLanguage: UiLanguage, now: Date = new Date()): string {
  const y = now.getFullYear()
  const m = String(now.getMonth() + 1).padStart(2, '0')
  const d = String(now.getDate()).padStart(2, '0')
  void uiLanguage
  return `nexus-yearbook-${y}-${m}-${d}.html`
}

export function renderYearbookHtml(
  snapshot: YearbookSnapshot,
  uiLanguage: UiLanguage,
): string {
  const locale = pickLocale(uiLanguage)
  const range = formatRange(snapshot.windowStart, snapshot.windowEnd, locale.dateLocale)

  return `<!DOCTYPE html>
<html lang="${escapeHtml(uiLanguage)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(locale.pageHeader)}</title>
  <style>${STYLES}</style>
</head>
<body>
  <main>
    <header class="title-page">
      <div class="eyebrow">Nexus</div>
      <h1>${escapeHtml(locale.pageHeader)}</h1>
      <div class="range">${escapeHtml(range)}</div>
    </header>
    ${renderYearOverview(snapshot, locale)}
    ${renderCoreg(snapshot, locale)}
    ${renderMonthly(snapshot, locale)}
    ${renderLetters(snapshot, locale)}
    ${renderClosing(locale)}
  </main>
  <footer>${escapeHtml(locale.footerCredit)}</footer>
</body>
</html>
`
}
